### PR TITLE
name added

### PR DESCRIPTION
**Pull request by msmillennialmom**

### CODE REVIEW

**Comment by msmillennialmom** [comment]
name added

**Comment by tkraak** [comment]
@msmillennialmom ... I see that you created a [`myname`](https://github.com/msmillennialmom/fewd-pull-request-exercise/tree/myname) branch, but then made your commit on [`master`](https://github.com/msmillennialmom/fewd-pull-request-exercise/tree/master). See if you can fix that.

**Comment by msmillennialmom** [comment]
@tkraak did i fail to commit the myname branch? I was a little confused as to which sequence to follow when committing the myname branch.

**Comment by tkraak** [comment]
@msmillennialmom ... don't worry about it for now. We'll go over the entire process step-by-step in class tomorrow.

**Pull request closed without merging**
